In [38]:
import torch
from torchmetrics.functional import precision
import numpy as np


a = torch.Tensor([[0.1], [0.2], [0.4], [-0.2]])
b = torch.Tensor([[-0.1], [0.4], [0.8], [-0.4]])

In [39]:
zeros = torch.zeros_like(a)
ones = torch.ones_like(a)
ones

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [40]:
a = torch.where(a>0, zeros, ones)
a = a.type(torch.LongTensor)
b = torch.where(b>0, zeros, ones)
b = b.type(torch.LongTensor)
a

tensor([[0],
        [0],
        [0],
        [1]])

In [41]:
b

tensor([[1],
        [0],
        [0],
        [1]])

In [42]:
precision(preds=a, target=b, average='none', num_classes=2)

tensor([0.6667, 1.0000])